<a href="https://colab.research.google.com/github/gabriellandimdonadel/Ciencia_dados_Aprendizagem_Maquina/blob/main/Pyton_para_ciencia_de_dados_IV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
cidades = pd.DataFrame(

[

['Paraná', 'Londrina', 575377, 1356.00],

['São Paulo', 'São Carlos', 254484, 1508.00],

['Santa Catarina', 'Florianópolis', 508826, 1798.00],

['Paraná', 'Curitiba', 1963726, 2293.00],

['São Paulo', 'Campinas', 1223237, 1710.00]

], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'])

cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [12]:
df = pd.read_csv('qualidade_vinho.csv', sep=';', header=0)
df.head(2)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5

In [14]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [15]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

      Estado    Cidade  Habitantes  Salário-Médio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

In [19]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [20]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [21]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'], dtype='object')

In [24]:
cidades['Salário-Médio'].describe()

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-Médio, dtype: float64

In [25]:
cidades.dtypes

cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [26]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')

cidades.dtypes

Estado            object
Cidade            object
Habitantes       float64
Salário-Médio    float64
dtype: object

In [29]:
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021',

'3-12-2021']

cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y')
cidades

           Estado         Cidade  Habitantes  Salário-Médio       Data
0          Paraná       Londrina    575377.0         1356.0 2021-08-03
1       São Paulo     São Carlos    254484.0         1508.0 2021-09-03
2  Santa Catarina  Florianópolis    508826.0         1798.0 2021-10-03
3          Paraná       Curitiba   1963726.0         2293.0 2021-11-03
4       São Paulo       Campinas   1223237.0         1710.0 2021-12-03

In [30]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y')

In [31]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data - Censo'}, inplace=True)

cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021

In [32]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']]

cidadesHab

   N Habitantes  Salário-Médio
0      575377.0         1356.0
1      254484.0         1508.0
2      508826.0         1798.0
3     1963726.0         2293.0
4     1223237.0         1710.0

In [33]:
cidades.loc[[1, 2]]

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021

In [34]:
cidades.loc[[1, 2]]

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021

In [35]:
cidades.iloc[:, 0:2]

           Estado         Cidade
0          Paraná       Londrina
1       São Paulo     São Carlos
2  Santa Catarina  Florianópolis
3          Paraná       Curitiba
4       São Paulo       Campinas

In [36]:
cidades.iloc[1:3, :3]

           Estado         Cidade  N Habitantes
1       São Paulo     São Carlos      254484.0
2  Santa Catarina  Florianópolis      508826.0

In [37]:
cidades.iloc[:, [1, 3, 0, 2]]

          Cidade  Salário-Médio          Estado  N Habitantes
0       Londrina         1356.0          Paraná      575377.0
1     São Carlos         1508.0       São Paulo      254484.0
2  Florianópolis         1798.0  Santa Catarina      508826.0
3       Curitiba         2293.0          Paraná     1963726.0
4       Campinas         1710.0       São Paulo     1223237.0

In [39]:
cidades.iloc[:, [1, 3, 0, 2]]
cidades.iloc[:, [1, 3, 0, 2]]

          Cidade  Salário-Médio          Estado  N Habitantes
0       Londrina         1356.0          Paraná      575377.0
1     São Carlos         1508.0       São Paulo      254484.0
2  Florianópolis         1798.0  Santa Catarina      508826.0
3       Curitiba         2293.0          Paraná     1963726.0
4       Campinas         1710.0       São Paulo     1223237.0

In [44]:
cidades = cidades.drop(['Sigla-Repetida'], axis=1)

cidades

KeyError: "['Sigla-Repetida'] not found in axis"

In [45]:
cidades.query('`Salário-Médio` > 1400.0')

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021

In [46]:
cidades.query('Estado == "São Paulo"')

      Estado      Cidade  N Habitantes  Salário-Médio Data - Censo
1  São Paulo  São Carlos      254484.0         1508.0   03-09-2021
4  São Paulo    Campinas     1223237.0         1710.0   03-12-2021

In [47]:
cidades.query('`N Habitantes` > 500000 and `N Habitantes` < 1300000')

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021

In [48]:
cidades.sort_values(by='Cidade', inplace=True)

cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021

In [49]:
cidades.sort_values(by='Salário-Médio', inplace=True)

cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021

In [50]:
cidades_salarios = pd.DataFrame(

[

['Paraná', 'Londrina', 1356.00],

['São Paulo', 'São Carlos', 1508.00],

['Santa Catarina', 'Florianópolis', 1798.00],

['Paraná', 'Curitiba', 2293.00],

['São Paulo', 'Campinas', 1710.00]

], columns=['Estado', 'Cidade', 'Salário-Médio'])

cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [51]:
cidades_pop = pd.DataFrame(

[

['Londrina', 575377],

['São Carlos', 254484],

['Florianópolis', 508826],

['Curitiba', 1963726],

['Campinas', 1223237]

], columns=['Cidade', 'Habitantes'])

cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [52]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade")

pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade",
how="outer")

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

In [53]:
cidades_df1 = pd.DataFrame(

[

['Londrina', 575377],

['São Carlos', 254484],

['Florianópolis', 508826],

], columns=['Cidade', 'Habitantes'])

cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [54]:
cidades_df2 = pd.DataFrame(

[

['Curitiba', 1963726],

['Campinas', 1223237]

], columns=['Cidade', 'Habitantes'])

cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [55]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [56]:
cidades.to_csv("my_df.csv")

cidades.to_html("my_df.html")

cidades.to_json("my_df.json")